
----------------Instrumented execution to record the trace-----------------
[RV-Predict] Log directory: /home/ecelrc/students/yxiong/softwaretesting/JaConTeBe/RV-Predict/test/derby1
[RV-Predict] Finished retransforming preloaded classes.
********************************
Starting test: derby4129
Expected bug type: deadlock
This test should finish in 30 seconds.
********************************

java.sql.SQLException: Java exception: 'ASSERT FAILED Attempted to latch page twice: org.apache.derby.shared.common.sanity.AssertFailure'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:95)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:87)
	at org.apache.derby.impl.jdbc.Util.javaException(Util.java:244)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:403)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:346)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2201)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:81)
	at org.apache.derby.impl.jdbc.EmbedResultSet.closeOnTransactionError(EmbedResultSet.java:4338)
	at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(EmbedResultSet.java:467)
	at org.apache.derby.impl.jdbc.EmbedResultSet.next(EmbedResultSet.java:371)
	at Derby4129$1.run(Derby4129.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: Java exception: 'ASSERT FAILED Attempted to latch page twice: org.apache.derby.shared.common.sanity.AssertFailure'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:119)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)
	... 11 more
Caused by: org.apache.derby.shared.common.sanity.AssertFailure: ASSERT FAILED Attempted to latch page twice
	at org.apache.derby.shared.common.sanity.SanityManager.THROWASSERT(SanityManager.java:162)
	at org.apache.derby.shared.common.sanity.SanityManager.THROWASSERT(SanityManager.java:147)
	at org.apache.derby.impl.store.raw.data.BasePage.setExclusive(BasePage.java:1609)
	at org.apache.derby.impl.store.raw.data.BaseContainer.latchPage(BaseContainer.java:527)
	at org.apache.derby.impl.store.raw.data.FileContainer.latchPage(FileContainer.java:3416)
	at org.apache.derby.impl.store.raw.data.FileContainer.getUserPage(FileContainer.java:2435)
	at org.apache.derby.impl.store.raw.data.FileContainer.getNextHeadPage(FileContainer.java:2745)
	at org.apache.derby.impl.store.raw.data.BaseContainer.getNextPage(BaseContainer.java:516)
	at org.apache.derby.impl.store.raw.data.BaseContainerHandle.getNextPage(BaseContainerHandle.java:364)
	at org.apache.derby.impl.store.access.conglomerate.GenericScanController.positionAtNextPage(GenericScanController.java:499)
	at org.apache.derby.impl.store.access.conglomerate.GenericScanController.fetchRows(GenericScanController.java:827)
	at org.apache.derby.impl.store.access.heap.HeapScan.fetchNextGroup(HeapScan.java:322)
	at org.apache.derby.impl.sql.execute.BulkTableScanResultSet.reloadArray(BulkTableScanResultSet.java:327)
	at org.apache.derby.impl.sql.execute.BulkTableScanResultSet.getNextRowCore(BulkTableScanResultSet.java:282)
	at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(BasicNoPutResultSetImpl.java:460)
	at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(EmbedResultSet.java:427)
	... 3 more
java.sql.SQLNonTransientConnectionException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:76)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:87)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:103)
	at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Util.java:207)
	at org.apache.derby.impl.jdbc.EmbedStatement.checkExecStatus(EmbedStatement.java:1426)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(EmbedPreparedStatement.java:1645)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeQuery(EmbedPreparedStatement.java:270)
	at Derby4129$1.run(Derby4129.java:60)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:119)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)
	... 8 more
Operations last 5 seconds: 26
  Errors: 24
Operations last 5 seconds: 0
Operations last 5 seconds: 0
Operations last 5 seconds: 0
Program has been forced to exit from deadlock.
